// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Fail fast with a clear message during dev/build if env vars are missing.
if (!SUPABASE_URL) {
  throw new Error(
    'VITE_SUPABASE_URL is required. Add it to `health-app-web/.env` or your environment. Example: VITE_SUPABASE_URL="https://your-project.supabase.co"'
  );
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'VITE_SUPABASE_PUBLISHABLE_KEY is required. Add it to `health-app-web/.env` or your environment.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});